datastream_username: 'admin'
datastream_password: 'admin'
user_lists:
  - 'L#H19599'
  - 'L#H19600'
  - 'L#H19601'
  - 'L#H19602'
  - 'L#H19603'
  - 'L#H19604'
  - 'L#H19605'
  - 'L#H19606'
economic_indicators:
  cpi:
    high: 19
    low: -20
    json_name: 'CPI'
  cab:
    high: 'NA'
    low: -12
    json_name: 'CAB'
  fiscal:
    high: 'NA'
    low: -11
    json_name: 'FB'
  fximports:
    high: 'NA'
    low: 2
    json_name: 'FXImports'
  fxdebt: 
    high: 'NA'
    low: 64
    json_name: 'FXDebt'
  credit:
    high: 39
    low: -14
    json_name: 'RDCG'
  gdp:
    high: 11
    low: 0
    json_name: 'RealGDP'
  interestrate:
    high: 24
    low: -10
    json_name: 'RealSTLR'
